## Services
google_analytics: 'UA-49193300-1'

## Meta
rss: https://jysperm.me/atom.xml
favicon: /avatars/v5.png
icon: /avatars/v5.png
source_url: 'https://github.com/jysperm/blog/blob/master/source/'
license:
  name: 'CC BY-NC-SA 3.0'
  url: 'http://creativecommons.org/licenses/by-nc-sa/3.0/cn'

## Menus
menus:
  '关于精子': /about
  '简历': /resume
  '链接': /links
  '推荐书单': /booklist
  '所有日志': /list
  '广告': /ad

right_menus:
  '彩排': /caipai
  'RSS': /atom.xml
  'fork on Github':
    target: '_blank'
    href: 'https://github.com/jysperm/blog'

## Banners && Widgets
banners:
  -
    jade: |
      | 我正在 SegmentFault 上录制一些 #[a(href='https://segmentfault.com/u/jysperm/lives?type=started') 视频课程]，欢迎购买收看，这是支持我创作更多技术内容的好机会哦。

  -
    jade: |
      | 基于业界最成熟的加密和版本控制工具 —— GPG 和 Git 的密码管理器：#[a(href='https://github.com/jysperm/elecpass') Elecpass]

widgets:
  -
    markdown: |
      精子生于 1995.11.25, 21 岁，英文 ID jysperm.

      * 有一个 [精子粉丝团](https://jybox.net)
      * [皮蛋](http://pidan.cat) 和 [豆腐](http://doufu.cat) 的主人
      * 创建了 [Atom 中文社区](https://atom-china.org)
      * 坚持十余年的 [独立博客](https://jysperm.me) 作者
      * 高中退学，就职于 [LeanCloud](https://leancloud.cn)
      * 在 [Github](https://github.com/jysperm) 上积极参与开源社区
  -
    jade: |
      h2 订阅推送
      p
        | 通过邮件订阅精子的博客日志、产品和项目的最新动态，精子承诺每一封邮件都会认真撰写（
        a(href='http://us13.campaign-archive1.com/home/?u=f4c7c26ec1a5dc400a7a7373e&id=e2136d8929') 历史邮件
        | ），有想和精子说的话也可以直接回复邮件。
      #mc_embed_signup
        form#mc-embedded-subscribe-form.validate(action='//jybox.us13.list-manage.com/subscribe/post?u=f4c7c26ec1a5dc400a7a7373e&id=e2136d8929', method='post', name='mc-embedded-subscribe-form', target='_blank', novalidate='')
          #mc_embed_signup_scroll.input-group
            input#mce-EMAIL.form-control(type='email', value='', name='EMAIL', placeholder='email address', required='')
            input(type='hidden', name='b_f4c7c26ec1a5dc400a7a7373e_e2136d8929', value='')
            span.input-group-button
              .form-actions
                button#mc-embedded-subscribe.btn(type='submit', value='Subscribe', name='subscribe') 订阅
  -
    tags: true
  -
    archives: true
  -
    copyright: true

## SNS
sns:
  qq: '184300584'
  qun: '61137226'
  v2ex: 'jybox'
  mobile: '17091927884'
  github: 'jysperm'
  keybase: 'jysperm'
  zhihu: 'jysperm'
  google_plus: '+王子亭jysperm'
  segmentfault: 'jysperm'
  twitter: 'jysperm'
  bitcoin: '13v2BTCMZMHg5v87susgg86HFZqXERuwUd'
